/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sunrisedentalclinic;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

/**
 *
 * @author Sadhu
 */
public class BillingFrame extends javax.swing.JFrame {
    private int loadedAppointmentId = 0;
    private int createdBillId = 0;
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillingFrame.class.getName());

    /**
     * Creates new form BillingFrame
     */
    public BillingFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAppointmentNumber = new javax.swing.JTextField();
        txtPatient = new javax.swing.JTextField();
        txtTreatment = new javax.swing.JTextField();
        txtConsultationFee = new javax.swing.JTextField();
        txtTreatmentFee = new javax.swing.JTextField();
        txtTotalAmount = new javax.swing.JTextField();
        btnLoad = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnCreateBill = new javax.swing.JButton();
        btnPrintBill = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SUNRISE DENTAL CLINIC BILLING MANAGEMENT");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Appointment Number:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Patient ID: ");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Treatment ID: ");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Consultation Fee:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Treatment Fee:");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Total Amount:");
        jLabel7.setToolTipText("");

        txtAppointmentNumber.setToolTipText("");

        txtPatient.setEditable(false);
        txtPatient.setToolTipText("");

        txtTreatment.setEditable(false);
        txtTreatment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTreatment.setToolTipText("");

        txtConsultationFee.setToolTipText("");

        txtTreatmentFee.setToolTipText("");

        txtTotalAmount.setEditable(false);
        txtTotalAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotalAmount.setToolTipText("");

        btnLoad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLoad.setText("Load");
        btnLoad.setToolTipText("");
        btnLoad.addActionListener(this::btnLoadActionPerformed);

        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.setToolTipText("");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        btnCreateBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCreateBill.setText("Create Bill");
        btnCreateBill.setToolTipText("");
        btnCreateBill.addActionListener(this::btnCreateBillActionPerformed);

        btnPrintBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPrintBill.setText("Print Bill");
        btnPrintBill.addActionListener(this::btnPrintBillActionPerformed);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setToolTipText("");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setToolTipText("");
        btnBack.addActionListener(this::btnBackActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTreatmentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAppointmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(256, 256, 256))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAppointmentNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtConsultationFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTreatmentFee, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrintBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        try {

        String consultationText =
                txtConsultationFee.getText().trim();

        String treatmentText =
                txtTreatmentFee.getText().trim();

        if (consultationText.isEmpty()
                || treatmentText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter Consultation Fee and Treatment Fee."
            );

            return;
        }

        double consultationFee =
                Double.parseDouble(consultationText);

        double treatmentFee =
                Double.parseDouble(treatmentText);

        if (consultationFee < 0 || treatmentFee < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Fees cannot be negative."
            );

            return;
        }

        double totalAmount =
                consultationFee + treatmentFee;

        txtTotalAmount.setText(
                String.format("%.2f", totalAmount)
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid numeric values for the fees."
        );
    }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {

        String appointmentNumber =
                txtAppointmentNumber.getText().trim();

        if (appointmentNumber.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter an Appointment Number."
            );

            txtAppointmentNumber.requestFocus();
            return;
        }

        if (!appointmentNumber.matches("[A-Za-z0-9-]+")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment Number can contain only letters, numbers and hyphens."
            );

            txtAppointmentNumber.requestFocus();
            return;
        }

        URL url = new URL(
                "http://localhost:8080/SunriseDentalServer/resources/appointments/"
                + appointmentNumber
        );

        HttpURLConnection conn =
                (HttpURLConnection) url.openConnection();

        conn.setRequestMethod("GET");
        conn.setRequestProperty(
                "Accept",
                "application/json"
        );

        int responseCode =
                conn.getResponseCode();

        if (responseCode == HttpURLConnection.HTTP_OK) {

            BufferedReader reader =
                    new BufferedReader(
                            new InputStreamReader(
                                    conn.getInputStream()
                            )
                    );

            StringBuilder response =
                    new StringBuilder();

            String line;

            while ((line = reader.readLine()) != null) {
                response.append(line);
            }

            reader.close();

            org.json.JSONObject appointment =
                    new org.json.JSONObject(
                            response.toString()
                    );
            loadedAppointmentId =
        appointment.getInt("appointmentId");

            txtPatient.setText(
                    String.valueOf(
                            appointment.getInt("patientId")
                    )
            );

            txtTreatment.setText(
                    String.valueOf(
                            appointment.getInt("treatmentId")
                    )
            );

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment loaded successfully."
            );

        } else if (responseCode ==
                HttpURLConnection.HTTP_NOT_FOUND) {

            JOptionPane.showMessageDialog(
                    this,
                    "Appointment not found."
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to load appointment.\n"
                    + "HTTP Status: "
                    + responseCode
            );
        }

        conn.disconnect();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage()
        );
    }

    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnCreateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBillActionPerformed
        try {

        // Check whether an appointment was loaded
        if (loadedAppointmentId == 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please load an appointment first."
            );

            return;
        }

        // Get fee values
        String consultationText =
                txtConsultationFee.getText().trim();

        String treatmentText =
                txtTreatmentFee.getText().trim();

        String totalText =
                txtTotalAmount.getText().trim();

        if (consultationText.isEmpty()
                || treatmentText.isEmpty()
                || totalText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please enter the fees and calculate the total first."
            );

            return;
        }

        double consultationFee =
                Double.parseDouble(consultationText);

        double treatmentFee =
                Double.parseDouble(treatmentText);

        double totalAmount =
                Double.parseDouble(totalText);

        if (consultationFee < 0
                || treatmentFee < 0) {

            JOptionPane.showMessageDialog(
                    this,
                    "Fees cannot be negative."
            );

            return;
        }

        // Prepare JSON
        org.json.JSONObject bill =
                new org.json.JSONObject();

        bill.put(
                "appointmentId",
                loadedAppointmentId
        );

        bill.put(
                "consultationFee",
                consultationFee
        );

        bill.put(
                "treatmentFee",
                treatmentFee
        );

        bill.put(
                "totalAmount",
                totalAmount
        );

        bill.put(
                "billDate",
                java.time.LocalDate.now().toString()
        );

        // Connect to REST API
        URL url = new URL(
                "http://localhost:8080/"
                + "SunriseDentalServer/resources/bills"
        );

        HttpURLConnection conn =
                (HttpURLConnection) url.openConnection();

        conn.setRequestMethod("POST");

        conn.setRequestProperty(
                "Content-Type",
                "application/json"
        );

        conn.setRequestProperty(
                "Accept",
                "application/json"
        );

        conn.setDoOutput(true);

        // Send JSON
        try (OutputStream os =
                conn.getOutputStream()) {

            byte[] input =
                    bill.toString()
                            .getBytes(
                                    StandardCharsets.UTF_8
                            );

            os.write(input);
        }

        int responseCode =
                conn.getResponseCode();

        if (responseCode ==
                HttpURLConnection.HTTP_CREATED) {

            BufferedReader reader =
                    new BufferedReader(
                            new InputStreamReader(
                                    conn.getInputStream()
                            )
                    );

            StringBuilder response =
                    new StringBuilder();

            String line;

            while ((line = reader.readLine()) != null) {
                response.append(line);
            }

            reader.close();

            org.json.JSONObject createdBill =
                    new org.json.JSONObject(
                            response.toString()
                    );

            int billId =
                    createdBill.getInt("billId");
            createdBillId = billId;

            JOptionPane.showMessageDialog(
                    this,
                    "Bill created successfully.\n"
                    + "Bill ID: " + billId
            );

        } else {

            JOptionPane.showMessageDialog(
                    this,
                    "Failed to create bill.\n"
                    + "HTTP Status: "
                    + responseCode
            );
        }

        conn.disconnect();

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Please enter valid numeric values for the fees."
        );

    } catch (Exception e) {

        JOptionPane.showMessageDialog(
                this,
                "Error creating bill: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnCreateBillActionPerformed

    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
        if (createdBillId == 0) {

        JOptionPane.showMessageDialog(
                this,
                "Please create the bill first."
        );

        return;
    }

    String receipt =
            "========================================\n"
            + "          SUNRISE DENTAL CLINIC\n"
            + "                BILL RECEIPT\n"
            + "========================================\n\n"
            + "Bill ID          : " + createdBillId + "\n"
            + "Appointment No   : "
            + txtAppointmentNumber.getText() + "\n"
            + "Patient ID       : "
            + txtPatient.getText() + "\n"
            + "Treatment ID     : "
            + txtTreatment.getText() + "\n\n"
            + "Consultation Fee : Rs. "
            + txtConsultationFee.getText() + "\n"
            + "Treatment Fee    : Rs. "
            + txtTreatmentFee.getText() + "\n"
            + "----------------------------------------\n"
            + "TOTAL            : Rs. "
            + txtTotalAmount.getText() + "\n"
            + "========================================\n\n"
            + "       Thank you for choosing us!\n";

    java.awt.print.PrinterJob printerJob =
            java.awt.print.PrinterJob.getPrinterJob();

    printerJob.setPrintable((graphics, pageFormat, pageIndex) -> {

        if (pageIndex > 0) {
            return java.awt.print.Printable.NO_SUCH_PAGE;
        }

        java.awt.Graphics2D g2 =
                (java.awt.Graphics2D) graphics;

        g2.translate(
                pageFormat.getImageableX(),
                pageFormat.getImageableY()
        );

        g2.setFont(
                new java.awt.Font(
                        "Monospaced",
                        java.awt.Font.PLAIN,
                        10
                )
        );

        int y = 20;

        for (String line : receipt.split("\n")) {

            g2.drawString(line, 10, y);

            y += 15;
        }

        return java.awt.print.Printable.PAGE_EXISTS;
    });

    if (printerJob.printDialog()) {

        try {

            printerJob.print();

            JOptionPane.showMessageDialog(
                    this,
                    "Bill printed successfully."
            );

        } catch (java.awt.print.PrinterException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Printing failed: "
                    + e.getMessage()
            );
        }
    }
    
    }//GEN-LAST:event_btnPrintBillActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtAppointmentNumber.setText("");
    txtPatient.setText("");
    txtTreatment.setText("");
    txtConsultationFee.setText("");
    txtTreatmentFee.setText("");
    txtTotalAmount.setText("");

    loadedAppointmentId = 0;
    createdBillId = 0;

    txtAppointmentNumber.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        DashboardFrame dashboard =
            new DashboardFrame();

    dashboard.setVisible(true);

    this.dispose();

    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillingFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateBill;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAppointmentNumber;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtPatient;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtTreatment;
    private javax.swing.JTextField txtTreatmentFee;
    // End of variables declaration//GEN-END:variables
}
